# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from custom_msgs/WorldObject.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class WorldObject(genpy.Message):
  _md5sum = "02bf617586369c005f6429b5354bd9ab"
  _type = "custom_msgs/WorldObject"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string objClass
float32 x
float32 y
float32 angle
float64 prob"""
  __slots__ = ['objClass','x','y','angle','prob']
  _slot_types = ['string','float32','float32','float32','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       objClass,x,y,angle,prob

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WorldObject, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.objClass is None:
        self.objClass = ''
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.angle is None:
        self.angle = 0.
      if self.prob is None:
        self.prob = 0.
    else:
      self.objClass = ''
      self.x = 0.
      self.y = 0.
      self.angle = 0.
      self.prob = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.objClass
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3fd().pack(_x.x, _x.y, _x.angle, _x.prob))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.objClass = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.objClass = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.x, _x.y, _x.angle, _x.prob,) = _get_struct_3fd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.objClass
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3fd().pack(_x.x, _x.y, _x.angle, _x.prob))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.objClass = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.objClass = str[start:end]
      _x = self
      start = end
      end += 20
      (_x.x, _x.y, _x.angle, _x.prob,) = _get_struct_3fd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3fd = None
def _get_struct_3fd():
    global _struct_3fd
    if _struct_3fd is None:
        _struct_3fd = struct.Struct("<3fd")
    return _struct_3fd
