// Generated by gencpp from file custom_msgs/ClearLaser.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_CLEARLASER_H
#define CUSTOM_MSGS_MESSAGE_CLEARLASER_H

#include <ros/service_traits.h>


#include <custom_msgs/ClearLaserRequest.h>
#include <custom_msgs/ClearLaserResponse.h>


namespace custom_msgs
{

struct ClearLaser
{

typedef ClearLaserRequest Request;
typedef ClearLaserResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClearLaser
} // namespace custom_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_msgs::ClearLaser > {
  static const char* value()
  {
    return "f427fbbf8b1198bb81f85f08fbb4a779";
  }

  static const char* value(const ::custom_msgs::ClearLaser&) { return value(); }
};

template<>
struct DataType< ::custom_msgs::ClearLaser > {
  static const char* value()
  {
    return "custom_msgs/ClearLaser";
  }

  static const char* value(const ::custom_msgs::ClearLaser&) { return value(); }
};


// service_traits::MD5Sum< ::custom_msgs::ClearLaserRequest> should match
// service_traits::MD5Sum< ::custom_msgs::ClearLaser >
template<>
struct MD5Sum< ::custom_msgs::ClearLaserRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::ClearLaser >::value();
  }
  static const char* value(const ::custom_msgs::ClearLaserRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::ClearLaserRequest> should match
// service_traits::DataType< ::custom_msgs::ClearLaser >
template<>
struct DataType< ::custom_msgs::ClearLaserRequest>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::ClearLaser >::value();
  }
  static const char* value(const ::custom_msgs::ClearLaserRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_msgs::ClearLaserResponse> should match
// service_traits::MD5Sum< ::custom_msgs::ClearLaser >
template<>
struct MD5Sum< ::custom_msgs::ClearLaserResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_msgs::ClearLaser >::value();
  }
  static const char* value(const ::custom_msgs::ClearLaserResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_msgs::ClearLaserResponse> should match
// service_traits::DataType< ::custom_msgs::ClearLaser >
template<>
struct DataType< ::custom_msgs::ClearLaserResponse>
{
  static const char* value()
  {
    return DataType< ::custom_msgs::ClearLaser >::value();
  }
  static const char* value(const ::custom_msgs::ClearLaserResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_CLEARLASER_H
