// Generated by gencpp from file custom_msgs/ClearLaserResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSGS_MESSAGE_CLEARLASERRESPONSE_H
#define CUSTOM_MSGS_MESSAGE_CLEARLASERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msgs
{
template <class ContainerAllocator>
struct ClearLaserResponse_
{
  typedef ClearLaserResponse_<ContainerAllocator> Type;

  ClearLaserResponse_()
    : b(0.0)  {
    }
  ClearLaserResponse_(const ContainerAllocator& _alloc)
    : b(0.0)  {
  (void)_alloc;
    }



   typedef float _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ClearLaserResponse_

typedef ::custom_msgs::ClearLaserResponse_<std::allocator<void> > ClearLaserResponse;

typedef boost::shared_ptr< ::custom_msgs::ClearLaserResponse > ClearLaserResponsePtr;
typedef boost::shared_ptr< ::custom_msgs::ClearLaserResponse const> ClearLaserResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msgs::ClearLaserResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msgs::ClearLaserResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::ClearLaserResponse_<ContainerAllocator2> & rhs)
{
  return lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msgs::ClearLaserResponse_<ContainerAllocator1> & lhs, const ::custom_msgs::ClearLaserResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2fa35766f3759aa2164b5f04811b518";
  }

  static const char* value(const ::custom_msgs::ClearLaserResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2fa35766f3759aaULL;
  static const uint64_t static_value2 = 0x2164b5f04811b518ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msgs/ClearLaserResponse";
  }

  static const char* value(const ::custom_msgs::ClearLaserResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 b\n"
;
  }

  static const char* value(const ::custom_msgs::ClearLaserResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClearLaserResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msgs::ClearLaserResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msgs::ClearLaserResponse_<ContainerAllocator>& v)
  {
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSGS_MESSAGE_CLEARLASERRESPONSE_H
